#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"


@protocol ASPDrawingObject
@end

@interface ASPDrawingObject : ASPObject


@property(nonatomic) NSArray<ASPLink>* renderLinks;

@property(nonatomic) NSNumber* width;

@property(nonatomic) NSNumber* height;

@property(nonatomic) ASPLink* oleDataLink;

@property(nonatomic) ASPLink* imageDataLink;

@property(nonatomic) ASPLink* link;

@end
