#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPBorder.h"
#import "ASPLink.h"
#import "ASPColor.h"


@protocol ASPFont
@end

@interface ASPFont : ASPObject


@property(nonatomic) NSNumber* allCaps;

@property(nonatomic) NSNumber* bidi;

@property(nonatomic) NSNumber* bold;

@property(nonatomic) NSNumber* boldBi;

@property(nonatomic) ASPBorder* border;

@property(nonatomic) ASPColor* color;

@property(nonatomic) NSNumber* complexScript;

@property(nonatomic) NSNumber* doubleStrikeThrough;

@property(nonatomic) NSNumber* emboss;

@property(nonatomic) NSNumber* engrave;

@property(nonatomic) NSNumber* hidden;

@property(nonatomic) ASPColor* highlightColor;

@property(nonatomic) NSNumber* italic;

@property(nonatomic) NSNumber* italicBi;

@property(nonatomic) NSNumber* kerning;

@property(nonatomic) NSNumber* localeId;

@property(nonatomic) NSNumber* localeIdBi;

@property(nonatomic) NSNumber* localeIdFarEast;

@property(nonatomic) NSString* name;

@property(nonatomic) NSString* nameAscii;

@property(nonatomic) NSString* nameBi;

@property(nonatomic) NSString* nameFarEast;

@property(nonatomic) NSString* nameOther;

@property(nonatomic) NSNumber* noProofing;

@property(nonatomic) NSNumber* outline;

@property(nonatomic) NSNumber* position;

@property(nonatomic) NSNumber* scaling;

@property(nonatomic) NSNumber* shadow;

@property(nonatomic) NSNumber* size;

@property(nonatomic) NSNumber* sizeBi;

@property(nonatomic) NSNumber* smallCaps;

@property(nonatomic) NSNumber* spacing;

@property(nonatomic) NSNumber* strikeThrough;

@property(nonatomic) NSString* styleIdentifier;

@property(nonatomic) NSString* styleName;

@property(nonatomic) NSNumber* subscript;

@property(nonatomic) NSNumber* superscript;

@property(nonatomic) NSString* textEffect;

@property(nonatomic) NSString* underline;

@property(nonatomic) ASPColor* underlineColor;

@property(nonatomic) ASPLink* link;

@end
