#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */



@protocol ASPReplaceTextRequest
@end

@interface ASPReplaceTextRequest : ASPObject


@property(nonatomic) NSString* oldValue;

@property(nonatomic) NSString* currentValue;

@property(nonatomic) NSNumber* isMatchCase;

@property(nonatomic) NSNumber* isMatchWholeWord;

@end
