#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPLink.h"
#import "ASPLinkElement.h"


@protocol ASPSection
@end

@interface ASPSection : ASPObject


@property(nonatomic) ASPLinkElement* paragraphs;

@property(nonatomic) ASPLinkElement* pageSetup;

@property(nonatomic) ASPLink* link;

@end
