<?php
namespace Aspose\Words\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Paragraph {
	static $swaggerTypes = array(
		'ChildNodes' => 'array[object]',
		'NodeId' => 'string',
		'link' => 'Link'

	);

	public $ChildNodes; // array[object]
	public $NodeId; // string
	public $link; // Link
	}

