<?php
namespace Aspose\Words\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class SaveOptionsData {
	static $swaggerTypes = array(
		'SaveFormat' => 'string',
		'FileName' => 'string',
		'DmlRenderingMode' => 'string',
		'DmlEffectsRenderingMode' => 'string',
		'ZipOutput' => 'bool'

	);

	public $SaveFormat; // string
	public $FileName; // string
	public $DmlRenderingMode; // string
	public $DmlEffectsRenderingMode; // string
	public $ZipOutput; // bool
	}

