<?php
namespace Aspose\Words\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class TiffSaveOptionsData {
	static $swaggerTypes = array(
		'TiffBinarizationMethod' => 'string',
		'TiffCompression' => 'string',
		'PageCount' => 'int',
		'PixelFormat' => 'string',
		'PaperColor' => 'string',
		'Resolution' => 'float',
		'Scale' => 'float',
		'ImageBrightness' => 'float',
		'ImageColorMode' => 'string',
		'ImageContrast' => 'float',
		'UseHighQualityRendering' => 'bool',
		'UseAntiAliasing' => 'bool',
		'PageIndex' => 'int',
		'MetafileRenderingOptions' => 'MetafileRenderingOptionsData',
		'NumeralFormat' => 'string',
		'SaveFormat' => 'string',
		'FileName' => 'string',
		'DmlRenderingMode' => 'string',
		'DmlEffectsRenderingMode' => 'string',
		'ZipOutput' => 'bool'

	);

	public $TiffBinarizationMethod; // string
	public $TiffCompression; // string
	public $PageCount; // int
	public $PixelFormat; // string
	public $PaperColor; // string
	public $Resolution; // float
	public $Scale; // float
	public $ImageBrightness; // float
	public $ImageColorMode; // string
	public $ImageContrast; // float
	public $UseHighQualityRendering; // bool
	public $UseAntiAliasing; // bool
	public $PageIndex; // int
	public $MetafileRenderingOptions; // MetafileRenderingOptionsData
	public $NumeralFormat; // string
	public $SaveFormat; // string
	public $FileName; // string
	public $DmlRenderingMode; // string
	public $DmlEffectsRenderingMode; // string
	public $ZipOutput; // bool
	}

