/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTOSavingMetafileRenderingOptionsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTOSavingMetafileRenderingOptionsDataTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTOSavingMetafileRenderingOptionsData
        //private AsposeWordsCloudDTOSavingMetafileRenderingOptionsData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTOSavingMetafileRenderingOptionsData
            //instance = new AsposeWordsCloudDTOSavingMetafileRenderingOptionsData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTOSavingMetafileRenderingOptionsData
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTOSavingMetafileRenderingOptionsDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTOSavingMetafileRenderingOptionsData
            //Assert.IsInstanceOfType<AsposeWordsCloudDTOSavingMetafileRenderingOptionsData> (instance, "variable 'instance' is a AsposeWordsCloudDTOSavingMetafileRenderingOptionsData");
        }

        /// <summary>
        /// Test the property 'EmfPlusDualRenderingMode'
        /// </summary>
        [Test]
        public void EmfPlusDualRenderingModeTest()
        {
            // TODO unit test for the property 'EmfPlusDualRenderingMode'
        }
        /// <summary>
        /// Test the property 'RenderingMode'
        /// </summary>
        [Test]
        public void RenderingModeTest()
        {
            // TODO unit test for the property 'RenderingMode'
        }
        /// <summary>
        /// Test the property 'UseEmfEmbeddedToWmf'
        /// </summary>
        [Test]
        public void UseEmfEmbeddedToWmfTest()
        {
            // TODO unit test for the property 'UseEmfEmbeddedToWmf'
        }

    }

}
