/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTOStatDataDocumentStatData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTOStatDataDocumentStatDataTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTOStatDataDocumentStatData
        //private AsposeWordsCloudDTOStatDataDocumentStatData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTOStatDataDocumentStatData
            //instance = new AsposeWordsCloudDTOStatDataDocumentStatData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTOStatDataDocumentStatData
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTOStatDataDocumentStatDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTOStatDataDocumentStatData
            //Assert.IsInstanceOfType<AsposeWordsCloudDTOStatDataDocumentStatData> (instance, "variable 'instance' is a AsposeWordsCloudDTOStatDataDocumentStatData");
        }

        /// <summary>
        /// Test the property 'WordCount'
        /// </summary>
        [Test]
        public void WordCountTest()
        {
            // TODO unit test for the property 'WordCount'
        }
        /// <summary>
        /// Test the property 'ParagraphCount'
        /// </summary>
        [Test]
        public void ParagraphCountTest()
        {
            // TODO unit test for the property 'ParagraphCount'
        }
        /// <summary>
        /// Test the property 'PageCount'
        /// </summary>
        [Test]
        public void PageCountTest()
        {
            // TODO unit test for the property 'PageCount'
        }
        /// <summary>
        /// Test the property 'FootnotesStatData'
        /// </summary>
        [Test]
        public void FootnotesStatDataTest()
        {
            // TODO unit test for the property 'FootnotesStatData'
        }
        /// <summary>
        /// Test the property 'PageStatData'
        /// </summary>
        [Test]
        public void PageStatDataTest()
        {
            // TODO unit test for the property 'PageStatData'
        }

    }

}
