/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTOModificationOperationResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTOModificationOperationResultTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTOModificationOperationResult
        //private AsposeWordsCloudDTOModificationOperationResult instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTOModificationOperationResult
            //instance = new AsposeWordsCloudDTOModificationOperationResult();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTOModificationOperationResult
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTOModificationOperationResultInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTOModificationOperationResult
            //Assert.IsInstanceOfType<AsposeWordsCloudDTOModificationOperationResult> (instance, "variable 'instance' is a AsposeWordsCloudDTOModificationOperationResult");
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Test]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
        /// <summary>
        /// Test the property 'Dest'
        /// </summary>
        [Test]
        public void DestTest()
        {
            // TODO unit test for the property 'Dest'
        }

    }

}
