/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTOSavingFixedPageSaveOptionsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTOSavingFixedPageSaveOptionsDataTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTOSavingFixedPageSaveOptionsData
        //private AsposeWordsCloudDTOSavingFixedPageSaveOptionsData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTOSavingFixedPageSaveOptionsData
            //instance = new AsposeWordsCloudDTOSavingFixedPageSaveOptionsData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTOSavingFixedPageSaveOptionsData
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTOSavingFixedPageSaveOptionsDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTOSavingFixedPageSaveOptionsData
            //Assert.IsInstanceOfType<AsposeWordsCloudDTOSavingFixedPageSaveOptionsData> (instance, "variable 'instance' is a AsposeWordsCloudDTOSavingFixedPageSaveOptionsData");
        }

        /// <summary>
        /// Test the property 'JpegQuality'
        /// </summary>
        [Test]
        public void JpegQualityTest()
        {
            // TODO unit test for the property 'JpegQuality'
        }
        /// <summary>
        /// Test the property 'MetafileRenderingOptions'
        /// </summary>
        [Test]
        public void MetafileRenderingOptionsTest()
        {
            // TODO unit test for the property 'MetafileRenderingOptions'
        }
        /// <summary>
        /// Test the property 'NumeralFormat'
        /// </summary>
        [Test]
        public void NumeralFormatTest()
        {
            // TODO unit test for the property 'NumeralFormat'
        }
        /// <summary>
        /// Test the property 'OptimizeOutput'
        /// </summary>
        [Test]
        public void OptimizeOutputTest()
        {
            // TODO unit test for the property 'OptimizeOutput'
        }
        /// <summary>
        /// Test the property 'PageCount'
        /// </summary>
        [Test]
        public void PageCountTest()
        {
            // TODO unit test for the property 'PageCount'
        }
        /// <summary>
        /// Test the property 'PageIndex'
        /// </summary>
        [Test]
        public void PageIndexTest()
        {
            // TODO unit test for the property 'PageIndex'
        }

    }

}
