/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTOSavingSaveOptionsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTOSavingSaveOptionsDataTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTOSavingSaveOptionsData
        //private AsposeWordsCloudDTOSavingSaveOptionsData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTOSavingSaveOptionsData
            //instance = new AsposeWordsCloudDTOSavingSaveOptionsData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTOSavingSaveOptionsData
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTOSavingSaveOptionsDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTOSavingSaveOptionsData
            //Assert.IsInstanceOfType<AsposeWordsCloudDTOSavingSaveOptionsData> (instance, "variable 'instance' is a AsposeWordsCloudDTOSavingSaveOptionsData");
        }

        /// <summary>
        /// Test the property 'ColorMode'
        /// </summary>
        [Test]
        public void ColorModeTest()
        {
            // TODO unit test for the property 'ColorMode'
        }
        /// <summary>
        /// Test the property 'SaveFormat'
        /// </summary>
        [Test]
        public void SaveFormatTest()
        {
            // TODO unit test for the property 'SaveFormat'
        }
        /// <summary>
        /// Test the property 'FileName'
        /// </summary>
        [Test]
        public void FileNameTest()
        {
            // TODO unit test for the property 'FileName'
        }
        /// <summary>
        /// Test the property 'DmlRenderingMode'
        /// </summary>
        [Test]
        public void DmlRenderingModeTest()
        {
            // TODO unit test for the property 'DmlRenderingMode'
        }
        /// <summary>
        /// Test the property 'DmlEffectsRenderingMode'
        /// </summary>
        [Test]
        public void DmlEffectsRenderingModeTest()
        {
            // TODO unit test for the property 'DmlEffectsRenderingMode'
        }
        /// <summary>
        /// Test the property 'ZipOutput'
        /// </summary>
        [Test]
        public void ZipOutputTest()
        {
            // TODO unit test for the property 'ZipOutput'
        }
        /// <summary>
        /// Test the property 'UpdateSdtContent'
        /// </summary>
        [Test]
        public void UpdateSdtContentTest()
        {
            // TODO unit test for the property 'UpdateSdtContent'
        }
        /// <summary>
        /// Test the property 'UpdateFields'
        /// </summary>
        [Test]
        public void UpdateFieldsTest()
        {
            // TODO unit test for the property 'UpdateFields'
        }

    }

}
