/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTODocumentElementsOficeMathObjectsOfficeMathObjectsCollectionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTODocumentElementsOficeMathObjectsOfficeMathObjectsCollectionDtoTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTODocumentElementsOficeMathObjectsOfficeMathObjectsCollectionDto
        //private AsposeWordsCloudDTODocumentElementsOficeMathObjectsOfficeMathObjectsCollectionDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTODocumentElementsOficeMathObjectsOfficeMathObjectsCollectionDto
            //instance = new AsposeWordsCloudDTODocumentElementsOficeMathObjectsOfficeMathObjectsCollectionDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTODocumentElementsOficeMathObjectsOfficeMathObjectsCollectionDto
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTODocumentElementsOficeMathObjectsOfficeMathObjectsCollectionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTODocumentElementsOficeMathObjectsOfficeMathObjectsCollectionDto
            //Assert.IsInstanceOfType<AsposeWordsCloudDTODocumentElementsOficeMathObjectsOfficeMathObjectsCollectionDto> (instance, "variable 'instance' is a AsposeWordsCloudDTODocumentElementsOficeMathObjectsOfficeMathObjectsCollectionDto");
        }

        /// <summary>
        /// Test the property 'List'
        /// </summary>
        [Test]
        public void ListTest()
        {
            // TODO unit test for the property 'List'
        }
        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Test]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }

    }

}
