/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTOSavingPdfEncryptionDetailsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTOSavingPdfEncryptionDetailsDataTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTOSavingPdfEncryptionDetailsData
        //private AsposeWordsCloudDTOSavingPdfEncryptionDetailsData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTOSavingPdfEncryptionDetailsData
            //instance = new AsposeWordsCloudDTOSavingPdfEncryptionDetailsData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTOSavingPdfEncryptionDetailsData
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTOSavingPdfEncryptionDetailsDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTOSavingPdfEncryptionDetailsData
            //Assert.IsInstanceOfType<AsposeWordsCloudDTOSavingPdfEncryptionDetailsData> (instance, "variable 'instance' is a AsposeWordsCloudDTOSavingPdfEncryptionDetailsData");
        }

        /// <summary>
        /// Test the property 'EncryptionAlgorithm'
        /// </summary>
        [Test]
        public void EncryptionAlgorithmTest()
        {
            // TODO unit test for the property 'EncryptionAlgorithm'
        }
        /// <summary>
        /// Test the property 'OwnerPassword'
        /// </summary>
        [Test]
        public void OwnerPasswordTest()
        {
            // TODO unit test for the property 'OwnerPassword'
        }
        /// <summary>
        /// Test the property 'Permissions'
        /// </summary>
        [Test]
        public void PermissionsTest()
        {
            // TODO unit test for the property 'Permissions'
        }
        /// <summary>
        /// Test the property 'UserPassword'
        /// </summary>
        [Test]
        public void UserPasswordTest()
        {
            // TODO unit test for the property 'UserPassword'
        }

    }

}
