/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTODocumentElementsCommentsCommentsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTODocumentElementsCommentsCommentsResponseTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTODocumentElementsCommentsCommentsResponse
        //private AsposeWordsCloudDTODocumentElementsCommentsCommentsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTODocumentElementsCommentsCommentsResponse
            //instance = new AsposeWordsCloudDTODocumentElementsCommentsCommentsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTODocumentElementsCommentsCommentsResponse
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTODocumentElementsCommentsCommentsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTODocumentElementsCommentsCommentsResponse
            //Assert.IsInstanceOfType<AsposeWordsCloudDTODocumentElementsCommentsCommentsResponse> (instance, "variable 'instance' is a AsposeWordsCloudDTODocumentElementsCommentsCommentsResponse");
        }

        /// <summary>
        /// Test the property 'Comments'
        /// </summary>
        [Test]
        public void CommentsTest()
        {
            // TODO unit test for the property 'Comments'
        }

    }

}
