/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTODocumentElementsTablesTableRowInsertDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTODocumentElementsTablesTableRowInsertDtoTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTODocumentElementsTablesTableRowInsertDto
        //private AsposeWordsCloudDTODocumentElementsTablesTableRowInsertDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTODocumentElementsTablesTableRowInsertDto
            //instance = new AsposeWordsCloudDTODocumentElementsTablesTableRowInsertDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTODocumentElementsTablesTableRowInsertDto
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTODocumentElementsTablesTableRowInsertDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTODocumentElementsTablesTableRowInsertDto
            //Assert.IsInstanceOfType<AsposeWordsCloudDTODocumentElementsTablesTableRowInsertDto> (instance, "variable 'instance' is a AsposeWordsCloudDTODocumentElementsTablesTableRowInsertDto");
        }

        /// <summary>
        /// Test the property 'InsertAfter'
        /// </summary>
        [Test]
        public void InsertAfterTest()
        {
            // TODO unit test for the property 'InsertAfter'
        }
        /// <summary>
        /// Test the property 'ColumnsCount'
        /// </summary>
        [Test]
        public void ColumnsCountTest()
        {
            // TODO unit test for the property 'ColumnsCount'
        }

    }

}
