/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTODocumentElementsFormFieldsFormFieldCheckbox
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTODocumentElementsFormFieldsFormFieldCheckboxTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTODocumentElementsFormFieldsFormFieldCheckbox
        //private AsposeWordsCloudDTODocumentElementsFormFieldsFormFieldCheckbox instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTODocumentElementsFormFieldsFormFieldCheckbox
            //instance = new AsposeWordsCloudDTODocumentElementsFormFieldsFormFieldCheckbox();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTODocumentElementsFormFieldsFormFieldCheckbox
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTODocumentElementsFormFieldsFormFieldCheckboxInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTODocumentElementsFormFieldsFormFieldCheckbox
            //Assert.IsInstanceOfType<AsposeWordsCloudDTODocumentElementsFormFieldsFormFieldCheckbox> (instance, "variable 'instance' is a AsposeWordsCloudDTODocumentElementsFormFieldsFormFieldCheckbox");
        }

        /// <summary>
        /// Test the property 'IsCheckBoxExactSize'
        /// </summary>
        [Test]
        public void IsCheckBoxExactSizeTest()
        {
            // TODO unit test for the property 'IsCheckBoxExactSize'
        }
        /// <summary>
        /// Test the property 'CheckBoxSize'
        /// </summary>
        [Test]
        public void CheckBoxSizeTest()
        {
            // TODO unit test for the property 'CheckBoxSize'
        }
        /// <summary>
        /// Test the property '_Checked'
        /// </summary>
        [Test]
        public void _CheckedTest()
        {
            // TODO unit test for the property '_Checked'
        }

    }

}
