/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTOSavingHtmlFixedSaveOptionsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTOSavingHtmlFixedSaveOptionsDataTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTOSavingHtmlFixedSaveOptionsData
        //private AsposeWordsCloudDTOSavingHtmlFixedSaveOptionsData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTOSavingHtmlFixedSaveOptionsData
            //instance = new AsposeWordsCloudDTOSavingHtmlFixedSaveOptionsData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTOSavingHtmlFixedSaveOptionsData
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTOSavingHtmlFixedSaveOptionsDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTOSavingHtmlFixedSaveOptionsData
            //Assert.IsInstanceOfType<AsposeWordsCloudDTOSavingHtmlFixedSaveOptionsData> (instance, "variable 'instance' is a AsposeWordsCloudDTOSavingHtmlFixedSaveOptionsData");
        }

        /// <summary>
        /// Test the property 'CssClassNamesPrefix'
        /// </summary>
        [Test]
        public void CssClassNamesPrefixTest()
        {
            // TODO unit test for the property 'CssClassNamesPrefix'
        }
        /// <summary>
        /// Test the property 'ExportEmbeddedCss'
        /// </summary>
        [Test]
        public void ExportEmbeddedCssTest()
        {
            // TODO unit test for the property 'ExportEmbeddedCss'
        }
        /// <summary>
        /// Test the property 'ExportEmbeddedFonts'
        /// </summary>
        [Test]
        public void ExportEmbeddedFontsTest()
        {
            // TODO unit test for the property 'ExportEmbeddedFonts'
        }
        /// <summary>
        /// Test the property 'ExportEmbeddedImages'
        /// </summary>
        [Test]
        public void ExportEmbeddedImagesTest()
        {
            // TODO unit test for the property 'ExportEmbeddedImages'
        }
        /// <summary>
        /// Test the property 'ExportFormFields'
        /// </summary>
        [Test]
        public void ExportFormFieldsTest()
        {
            // TODO unit test for the property 'ExportFormFields'
        }
        /// <summary>
        /// Test the property 'Encoding'
        /// </summary>
        [Test]
        public void EncodingTest()
        {
            // TODO unit test for the property 'Encoding'
        }
        /// <summary>
        /// Test the property 'FontFormat'
        /// </summary>
        [Test]
        public void FontFormatTest()
        {
            // TODO unit test for the property 'FontFormat'
        }
        /// <summary>
        /// Test the property 'ResourcesFolder'
        /// </summary>
        [Test]
        public void ResourcesFolderTest()
        {
            // TODO unit test for the property 'ResourcesFolder'
        }
        /// <summary>
        /// Test the property 'ResourcesFolderAlias'
        /// </summary>
        [Test]
        public void ResourcesFolderAliasTest()
        {
            // TODO unit test for the property 'ResourcesFolderAlias'
        }
        /// <summary>
        /// Test the property 'ShowPageBorder'
        /// </summary>
        [Test]
        public void ShowPageBorderTest()
        {
            // TODO unit test for the property 'ShowPageBorder'
        }
        /// <summary>
        /// Test the property 'PageHorizontalAlignment'
        /// </summary>
        [Test]
        public void PageHorizontalAlignmentTest()
        {
            // TODO unit test for the property 'PageHorizontalAlignment'
        }
        /// <summary>
        /// Test the property 'PageMargins'
        /// </summary>
        [Test]
        public void PageMarginsTest()
        {
            // TODO unit test for the property 'PageMargins'
        }

    }

}
