/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTOProtectionResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTOProtectionResponseTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTOProtectionResponse
        //private AsposeWordsCloudDTOProtectionResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTOProtectionResponse
            //instance = new AsposeWordsCloudDTOProtectionResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTOProtectionResponse
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTOProtectionResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTOProtectionResponse
            //Assert.IsInstanceOfType<AsposeWordsCloudDTOProtectionResponse> (instance, "variable 'instance' is a AsposeWordsCloudDTOProtectionResponse");
        }

        /// <summary>
        /// Test the property 'ProtectionResult'
        /// </summary>
        [Test]
        public void ProtectionResultTest()
        {
            // TODO unit test for the property 'ProtectionResult'
        }
        /// <summary>
        /// Test the property 'DocumentLink'
        /// </summary>
        [Test]
        public void DocumentLinkTest()
        {
            // TODO unit test for the property 'DocumentLink'
        }

    }

}
