/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTODocumentElementsCommentsCommentDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTODocumentElementsCommentsCommentDtoTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTODocumentElementsCommentsCommentDto
        //private AsposeWordsCloudDTODocumentElementsCommentsCommentDto instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTODocumentElementsCommentsCommentDto
            //instance = new AsposeWordsCloudDTODocumentElementsCommentsCommentDto();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTODocumentElementsCommentsCommentDto
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTODocumentElementsCommentsCommentDtoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTODocumentElementsCommentsCommentDto
            //Assert.IsInstanceOfType<AsposeWordsCloudDTODocumentElementsCommentsCommentDto> (instance, "variable 'instance' is a AsposeWordsCloudDTODocumentElementsCommentsCommentDto");
        }

        /// <summary>
        /// Test the property 'RangeStart'
        /// </summary>
        [Test]
        public void RangeStartTest()
        {
            // TODO unit test for the property 'RangeStart'
        }
        /// <summary>
        /// Test the property 'RangeEnd'
        /// </summary>
        [Test]
        public void RangeEndTest()
        {
            // TODO unit test for the property 'RangeEnd'
        }
        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Test]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }
        /// <summary>
        /// Test the property 'Initial'
        /// </summary>
        [Test]
        public void InitialTest()
        {
            // TODO unit test for the property 'Initial'
        }
        /// <summary>
        /// Test the property 'DateTime'
        /// </summary>
        [Test]
        public void DateTimeTest()
        {
            // TODO unit test for the property 'DateTime'
        }
        /// <summary>
        /// Test the property 'Text'
        /// </summary>
        [Test]
        public void TextTest()
        {
            // TODO unit test for the property 'Text'
        }
        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Test]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }
        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Test]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }

    }

}
