/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTOSearchSearchResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTOSearchSearchResponseTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTOSearchSearchResponse
        //private AsposeWordsCloudDTOSearchSearchResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTOSearchSearchResponse
            //instance = new AsposeWordsCloudDTOSearchSearchResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTOSearchSearchResponse
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTOSearchSearchResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTOSearchSearchResponse
            //Assert.IsInstanceOfType<AsposeWordsCloudDTOSearchSearchResponse> (instance, "variable 'instance' is a AsposeWordsCloudDTOSearchSearchResponse");
        }

        /// <summary>
        /// Test the property 'SearchingPattern'
        /// </summary>
        [Test]
        public void SearchingPatternTest()
        {
            // TODO unit test for the property 'SearchingPattern'
        }
        /// <summary>
        /// Test the property 'SearchResults'
        /// </summary>
        [Test]
        public void SearchResultsTest()
        {
            // TODO unit test for the property 'SearchResults'
        }

    }

}
