/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTODocumentElementsSectionsPageSetup
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTODocumentElementsSectionsPageSetupTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTODocumentElementsSectionsPageSetup
        //private AsposeWordsCloudDTODocumentElementsSectionsPageSetup instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTODocumentElementsSectionsPageSetup
            //instance = new AsposeWordsCloudDTODocumentElementsSectionsPageSetup();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTODocumentElementsSectionsPageSetup
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTODocumentElementsSectionsPageSetupInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTODocumentElementsSectionsPageSetup
            //Assert.IsInstanceOfType<AsposeWordsCloudDTODocumentElementsSectionsPageSetup> (instance, "variable 'instance' is a AsposeWordsCloudDTODocumentElementsSectionsPageSetup");
        }

        /// <summary>
        /// Test the property 'Bidi'
        /// </summary>
        [Test]
        public void BidiTest()
        {
            // TODO unit test for the property 'Bidi'
        }
        /// <summary>
        /// Test the property 'BorderAlwaysInFront'
        /// </summary>
        [Test]
        public void BorderAlwaysInFrontTest()
        {
            // TODO unit test for the property 'BorderAlwaysInFront'
        }
        /// <summary>
        /// Test the property 'BorderAppliesTo'
        /// </summary>
        [Test]
        public void BorderAppliesToTest()
        {
            // TODO unit test for the property 'BorderAppliesTo'
        }
        /// <summary>
        /// Test the property 'BorderDistanceFrom'
        /// </summary>
        [Test]
        public void BorderDistanceFromTest()
        {
            // TODO unit test for the property 'BorderDistanceFrom'
        }
        /// <summary>
        /// Test the property 'BottomMargin'
        /// </summary>
        [Test]
        public void BottomMarginTest()
        {
            // TODO unit test for the property 'BottomMargin'
        }
        /// <summary>
        /// Test the property 'DifferentFirstPageHeaderFooter'
        /// </summary>
        [Test]
        public void DifferentFirstPageHeaderFooterTest()
        {
            // TODO unit test for the property 'DifferentFirstPageHeaderFooter'
        }
        /// <summary>
        /// Test the property 'FirstPageTray'
        /// </summary>
        [Test]
        public void FirstPageTrayTest()
        {
            // TODO unit test for the property 'FirstPageTray'
        }
        /// <summary>
        /// Test the property 'FooterDistance'
        /// </summary>
        [Test]
        public void FooterDistanceTest()
        {
            // TODO unit test for the property 'FooterDistance'
        }
        /// <summary>
        /// Test the property 'Gutter'
        /// </summary>
        [Test]
        public void GutterTest()
        {
            // TODO unit test for the property 'Gutter'
        }
        /// <summary>
        /// Test the property 'HeaderDistance'
        /// </summary>
        [Test]
        public void HeaderDistanceTest()
        {
            // TODO unit test for the property 'HeaderDistance'
        }
        /// <summary>
        /// Test the property 'LeftMargin'
        /// </summary>
        [Test]
        public void LeftMarginTest()
        {
            // TODO unit test for the property 'LeftMargin'
        }
        /// <summary>
        /// Test the property 'LineNumberCountBy'
        /// </summary>
        [Test]
        public void LineNumberCountByTest()
        {
            // TODO unit test for the property 'LineNumberCountBy'
        }
        /// <summary>
        /// Test the property 'LineNumberDistanceFromText'
        /// </summary>
        [Test]
        public void LineNumberDistanceFromTextTest()
        {
            // TODO unit test for the property 'LineNumberDistanceFromText'
        }
        /// <summary>
        /// Test the property 'LineNumberRestartMode'
        /// </summary>
        [Test]
        public void LineNumberRestartModeTest()
        {
            // TODO unit test for the property 'LineNumberRestartMode'
        }
        /// <summary>
        /// Test the property 'LineStartingNumber'
        /// </summary>
        [Test]
        public void LineStartingNumberTest()
        {
            // TODO unit test for the property 'LineStartingNumber'
        }
        /// <summary>
        /// Test the property 'Orientation'
        /// </summary>
        [Test]
        public void OrientationTest()
        {
            // TODO unit test for the property 'Orientation'
        }
        /// <summary>
        /// Test the property 'OtherPagesTray'
        /// </summary>
        [Test]
        public void OtherPagesTrayTest()
        {
            // TODO unit test for the property 'OtherPagesTray'
        }
        /// <summary>
        /// Test the property 'PageHeight'
        /// </summary>
        [Test]
        public void PageHeightTest()
        {
            // TODO unit test for the property 'PageHeight'
        }
        /// <summary>
        /// Test the property 'PageNumberStyle'
        /// </summary>
        [Test]
        public void PageNumberStyleTest()
        {
            // TODO unit test for the property 'PageNumberStyle'
        }
        /// <summary>
        /// Test the property 'PageStartingNumber'
        /// </summary>
        [Test]
        public void PageStartingNumberTest()
        {
            // TODO unit test for the property 'PageStartingNumber'
        }
        /// <summary>
        /// Test the property 'PageWidth'
        /// </summary>
        [Test]
        public void PageWidthTest()
        {
            // TODO unit test for the property 'PageWidth'
        }
        /// <summary>
        /// Test the property 'PaperSize'
        /// </summary>
        [Test]
        public void PaperSizeTest()
        {
            // TODO unit test for the property 'PaperSize'
        }
        /// <summary>
        /// Test the property 'RestartPageNumbering'
        /// </summary>
        [Test]
        public void RestartPageNumberingTest()
        {
            // TODO unit test for the property 'RestartPageNumbering'
        }
        /// <summary>
        /// Test the property 'RightMargin'
        /// </summary>
        [Test]
        public void RightMarginTest()
        {
            // TODO unit test for the property 'RightMargin'
        }
        /// <summary>
        /// Test the property 'RtlGutter'
        /// </summary>
        [Test]
        public void RtlGutterTest()
        {
            // TODO unit test for the property 'RtlGutter'
        }
        /// <summary>
        /// Test the property 'SectionStart'
        /// </summary>
        [Test]
        public void SectionStartTest()
        {
            // TODO unit test for the property 'SectionStart'
        }
        /// <summary>
        /// Test the property 'SuppressEndnotes'
        /// </summary>
        [Test]
        public void SuppressEndnotesTest()
        {
            // TODO unit test for the property 'SuppressEndnotes'
        }
        /// <summary>
        /// Test the property 'TopMargin'
        /// </summary>
        [Test]
        public void TopMarginTest()
        {
            // TODO unit test for the property 'TopMargin'
        }
        /// <summary>
        /// Test the property 'VerticalAlignment'
        /// </summary>
        [Test]
        public void VerticalAlignmentTest()
        {
            // TODO unit test for the property 'VerticalAlignment'
        }
        /// <summary>
        /// Test the property 'Link'
        /// </summary>
        [Test]
        public void LinkTest()
        {
            // TODO unit test for the property 'Link'
        }

    }

}
