/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTOSavingDownsampleOptionsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTOSavingDownsampleOptionsDataTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTOSavingDownsampleOptionsData
        //private AsposeWordsCloudDTOSavingDownsampleOptionsData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTOSavingDownsampleOptionsData
            //instance = new AsposeWordsCloudDTOSavingDownsampleOptionsData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTOSavingDownsampleOptionsData
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTOSavingDownsampleOptionsDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTOSavingDownsampleOptionsData
            //Assert.IsInstanceOfType<AsposeWordsCloudDTOSavingDownsampleOptionsData> (instance, "variable 'instance' is a AsposeWordsCloudDTOSavingDownsampleOptionsData");
        }

        /// <summary>
        /// Test the property 'DownsampleImages'
        /// </summary>
        [Test]
        public void DownsampleImagesTest()
        {
            // TODO unit test for the property 'DownsampleImages'
        }
        /// <summary>
        /// Test the property 'Resolution'
        /// </summary>
        [Test]
        public void ResolutionTest()
        {
            // TODO unit test for the property 'Resolution'
        }
        /// <summary>
        /// Test the property 'ResolutionThreshold'
        /// </summary>
        [Test]
        public void ResolutionThresholdTest()
        {
            // TODO unit test for the property 'ResolutionThreshold'
        }

    }

}
