/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTOCommonLink
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTOCommonLinkTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTOCommonLink
        //private AsposeWordsCloudDTOCommonLink instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTOCommonLink
            //instance = new AsposeWordsCloudDTOCommonLink();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTOCommonLink
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTOCommonLinkInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTOCommonLink
            //Assert.IsInstanceOfType<AsposeWordsCloudDTOCommonLink> (instance, "variable 'instance' is a AsposeWordsCloudDTOCommonLink");
        }

        /// <summary>
        /// Test the property 'Href'
        /// </summary>
        [Test]
        public void HrefTest()
        {
            // TODO unit test for the property 'Href'
        }
        /// <summary>
        /// Test the property 'Rel'
        /// </summary>
        [Test]
        public void RelTest()
        {
            // TODO unit test for the property 'Rel'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Test]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Test]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

    }

}
