/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.com.aspose;
using IO.Swagger.Client;
using System.Reflection;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing AsposeWordsCloudDTOSavingOutlineOptionsData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class AsposeWordsCloudDTOSavingOutlineOptionsDataTests
    {
        // TODO uncomment below to declare an instance variable for AsposeWordsCloudDTOSavingOutlineOptionsData
        //private AsposeWordsCloudDTOSavingOutlineOptionsData instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of AsposeWordsCloudDTOSavingOutlineOptionsData
            //instance = new AsposeWordsCloudDTOSavingOutlineOptionsData();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of AsposeWordsCloudDTOSavingOutlineOptionsData
        /// </summary>
        [Test]
        public void AsposeWordsCloudDTOSavingOutlineOptionsDataInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" AsposeWordsCloudDTOSavingOutlineOptionsData
            //Assert.IsInstanceOfType<AsposeWordsCloudDTOSavingOutlineOptionsData> (instance, "variable 'instance' is a AsposeWordsCloudDTOSavingOutlineOptionsData");
        }

        /// <summary>
        /// Test the property 'BookmarksOutlineLevels'
        /// </summary>
        [Test]
        public void BookmarksOutlineLevelsTest()
        {
            // TODO unit test for the property 'BookmarksOutlineLevels'
        }
        /// <summary>
        /// Test the property 'DefaultBookmarksOutlineLevel'
        /// </summary>
        [Test]
        public void DefaultBookmarksOutlineLevelTest()
        {
            // TODO unit test for the property 'DefaultBookmarksOutlineLevel'
        }
        /// <summary>
        /// Test the property 'ExpandedOutlineLevels'
        /// </summary>
        [Test]
        public void ExpandedOutlineLevelsTest()
        {
            // TODO unit test for the property 'ExpandedOutlineLevels'
        }
        /// <summary>
        /// Test the property 'HeadingsOutlineLevels'
        /// </summary>
        [Test]
        public void HeadingsOutlineLevelsTest()
        {
            // TODO unit test for the property 'HeadingsOutlineLevels'
        }

    }

}
