#!/usr/bin/env python

class PageStatData(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'PageNumber': 'int',
            'WordCount': 'int',
            'ParagraphCount': 'int'

        }

        self.attributeMap = {
            'PageNumber': 'PageNumber','WordCount': 'WordCount','ParagraphCount': 'ParagraphCount'}       

        self.PageNumber = None # int
        self.WordCount = None # int
        self.ParagraphCount = None # int
        
