#!/usr/bin/env python

class Section(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'Paragraphs': 'LinkElement',
            'PageSetup': 'LinkElement',
            'link': 'Link'

        }

        self.attributeMap = {
            'Paragraphs': 'Paragraphs','PageSetup': 'PageSetup','link': 'link'}       

        self.Paragraphs = None # LinkElement
        self.PageSetup = None # LinkElement
        self.link = None # Link
        
