<?php
namespace Aspose\Words\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class Document {
	static $swaggerTypes = array(
		'Links' => 'array[Link]',
		'FileName' => 'string',
		'SourceFormat' => 'DocumentFormat',
		'IsEncrypted' => 'bool',
		'IsSigned' => 'bool',
		'DocumentProperties' => 'DocumentProperties'

	);

	public $Links; // array[Link]
	public $FileName; // string
	public $SourceFormat; // DocumentFormat
	public $IsEncrypted; // bool
	public $IsSigned; // bool
	public $DocumentProperties; // DocumentProperties
	}

