<?php
namespace Aspose\Words\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class DocumentProperties {
	static $swaggerTypes = array(
		'List' => 'array[DocumentProperty]',
		'link' => 'Link'

	);

	public $List; // array[DocumentProperty]
	public $link; // Link
	}

