<?php
namespace Aspose\Words\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class FieldNames {
	static $swaggerTypes = array(
		'Names' => 'array[string]',
		'link' => 'Link'

	);

	public $Names; // array[string]
	public $link; // Link
	}

