<?php
namespace Aspose\Words\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class HyperlinksResponse {
	static $swaggerTypes = array(
		'Hyperlinks' => 'Hyperlinks',
		'Code' => 'string',
		'Status' => 'string'

	);

	public $Hyperlinks; // Hyperlinks
	public $Code; // string
	public $Status; // string
	}

