<?php
namespace Aspose\Words\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class MetafileRenderingOptionsData {
	static $swaggerTypes = array(
		'EmfPlusDualRenderingMode' => 'string',
		'RenderingMode' => 'string',
		'UseEmfEmbeddedToWmf' => 'bool'

	);

	public $EmfPlusDualRenderingMode; // string
	public $RenderingMode; // string
	public $UseEmfEmbeddedToWmf; // bool
	}

