<?php
namespace Aspose\Words\Models;
/**
 * $model.description$
 *
 * NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
 *
 */
class ParagraphLink {
	static $swaggerTypes = array(
		'Text' => 'string',
		'link' => 'Link'

	);

	public $Text; // string
	public $link; // Link
	}

