#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPNodeLink.h"


@protocol ASPDocumentPosition
@end

@interface ASPDocumentPosition : ASPObject


@property(nonatomic) ASPNodeLink* node;

@property(nonatomic) NSNumber* offset;

@end
