#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPSaveOptionsData.h"


@protocol ASPLoadWebDocumentData
@end

@interface ASPLoadWebDocumentData : ASPObject


@property(nonatomic) NSString* loadingDocumentUrl;

@property(nonatomic) ASPSaveOptionsData* saveOptions;

@end
