#import <Foundation/Foundation.h>
#import "ASPObject.h"

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

#import "ASPColor.h"
#import "ASPMetafileRenderingOptionsData.h"


@protocol ASPTiffSaveOptionsData
@end

@interface ASPTiffSaveOptionsData : ASPObject


@property(nonatomic) NSString* tiffBinarizationMethod;

@property(nonatomic) NSString* tiffCompression;

@property(nonatomic) NSNumber* pageCount;

@property(nonatomic) NSString* pixelFormat;

@property(nonatomic) ASPColor* paperColor;

@property(nonatomic) NSNumber* resolution;

@property(nonatomic) NSNumber* scale;

@property(nonatomic) NSNumber* imageBrightness;

@property(nonatomic) NSString* imageColorMode;

@property(nonatomic) NSNumber* imageContrast;

@property(nonatomic) NSNumber* useHighQualityRendering;

@property(nonatomic) NSNumber* useAntiAliasing;

@property(nonatomic) NSNumber* pageIndex;

@property(nonatomic) ASPMetafileRenderingOptionsData* metafileRenderingOptions;

@property(nonatomic) NSString* numeralFormat;

@property(nonatomic) NSString* saveFormat;

@property(nonatomic) NSString* fileName;

@property(nonatomic) NSString* dmlRenderingMode;

@property(nonatomic) NSString* dmlEffectsRenderingMode;

@property(nonatomic) NSNumber* zipOutput;

@end
