/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.com.aspose
{
    /// <summary>
    /// Container for the footnotes statistical data
    /// </summary>
    [DataContract]
    public partial class AsposeWordsCloudDTOStatDataFootnotesStatData :  IEquatable<AsposeWordsCloudDTOStatDataFootnotesStatData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AsposeWordsCloudDTOStatDataFootnotesStatData" /> class.
        /// </summary>
        /// <param name="WordCount">Total count of words in footnotes.</param>
        /// <param name="ParagraphCount">Total count of paragraphs in footnotes.</param>
        public AsposeWordsCloudDTOStatDataFootnotesStatData(int? WordCount = default(int?), int? ParagraphCount = default(int?))
        {
            this.WordCount = WordCount;
            this.ParagraphCount = ParagraphCount;
        }
        
        /// <summary>
        /// Total count of words in footnotes
        /// </summary>
        /// <value>Total count of words in footnotes</value>
        [DataMember(Name="WordCount", EmitDefaultValue=false)]
        public int? WordCount { get; set; }

        /// <summary>
        /// Total count of paragraphs in footnotes
        /// </summary>
        /// <value>Total count of paragraphs in footnotes</value>
        [DataMember(Name="ParagraphCount", EmitDefaultValue=false)]
        public int? ParagraphCount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AsposeWordsCloudDTOStatDataFootnotesStatData {\n");
            sb.Append("  WordCount: ").Append(WordCount).Append("\n");
            sb.Append("  ParagraphCount: ").Append(ParagraphCount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AsposeWordsCloudDTOStatDataFootnotesStatData);
        }

        /// <summary>
        /// Returns true if AsposeWordsCloudDTOStatDataFootnotesStatData instances are equal
        /// </summary>
        /// <param name="other">Instance of AsposeWordsCloudDTOStatDataFootnotesStatData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AsposeWordsCloudDTOStatDataFootnotesStatData other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.WordCount == other.WordCount ||
                    this.WordCount != null &&
                    this.WordCount.Equals(other.WordCount)
                ) && 
                (
                    this.ParagraphCount == other.ParagraphCount ||
                    this.ParagraphCount != null &&
                    this.ParagraphCount.Equals(other.ParagraphCount)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.WordCount != null)
                    hash = hash * 59 + this.WordCount.GetHashCode();
                if (this.ParagraphCount != null)
                    hash = hash * 59 + this.ParagraphCount.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
