/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.com.aspose
{
    /// <summary>
    /// Response for the request of the document&#39;s statistical data
    /// </summary>
    [DataContract]
    public partial class AsposeWordsCloudDTOStatDataResponse :  IEquatable<AsposeWordsCloudDTOStatDataResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AsposeWordsCloudDTOStatDataResponse" /> class.
        /// </summary>
        /// <param name="StatData">Statistical data of the document.</param>
        /// <param name="DocumentLink">Link to the document.</param>
        public AsposeWordsCloudDTOStatDataResponse(AsposeWordsCloudDTOStatDataDocumentStatData StatData = default(AsposeWordsCloudDTOStatDataDocumentStatData), AsposeWordsCloudDTOCommonFileLink DocumentLink = default(AsposeWordsCloudDTOCommonFileLink))
        {
            this.StatData = StatData;
            this.DocumentLink = DocumentLink;
        }
        
        /// <summary>
        /// Statistical data of the document
        /// </summary>
        /// <value>Statistical data of the document</value>
        [DataMember(Name="StatData", EmitDefaultValue=false)]
        public AsposeWordsCloudDTOStatDataDocumentStatData StatData { get; set; }

        /// <summary>
        /// Link to the document
        /// </summary>
        /// <value>Link to the document</value>
        [DataMember(Name="DocumentLink", EmitDefaultValue=false)]
        public AsposeWordsCloudDTOCommonFileLink DocumentLink { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AsposeWordsCloudDTOStatDataResponse {\n");
            sb.Append("  StatData: ").Append(StatData).Append("\n");
            sb.Append("  DocumentLink: ").Append(DocumentLink).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AsposeWordsCloudDTOStatDataResponse);
        }

        /// <summary>
        /// Returns true if AsposeWordsCloudDTOStatDataResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of AsposeWordsCloudDTOStatDataResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AsposeWordsCloudDTOStatDataResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.StatData == other.StatData ||
                    this.StatData != null &&
                    this.StatData.Equals(other.StatData)
                ) && 
                (
                    this.DocumentLink == other.DocumentLink ||
                    this.DocumentLink != null &&
                    this.DocumentLink.Equals(other.DocumentLink)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.StatData != null)
                    hash = hash * 59 + this.StatData.GetHashCode();
                if (this.DocumentLink != null)
                    hash = hash * 59 + this.DocumentLink.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
