/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.com.aspose
{
    /// <summary>
    /// Result of search operation.
    /// </summary>
    [DataContract]
    public partial class AsposeWordsCloudDTOSearchSearchResult :  IEquatable<AsposeWordsCloudDTOSearchSearchResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AsposeWordsCloudDTOSearchSearchResult" /> class.
        /// </summary>
        /// <param name="RangeStart">Link to result range start node..</param>
        /// <param name="RangeEnd">Link to result range end node..</param>
        public AsposeWordsCloudDTOSearchSearchResult(AsposeWordsCloudDTODocumentPositionDto RangeStart = default(AsposeWordsCloudDTODocumentPositionDto), AsposeWordsCloudDTODocumentPositionDto RangeEnd = default(AsposeWordsCloudDTODocumentPositionDto))
        {
            this.RangeStart = RangeStart;
            this.RangeEnd = RangeEnd;
        }
        
        /// <summary>
        /// Link to result range start node.
        /// </summary>
        /// <value>Link to result range start node.</value>
        [DataMember(Name="RangeStart", EmitDefaultValue=false)]
        public AsposeWordsCloudDTODocumentPositionDto RangeStart { get; set; }

        /// <summary>
        /// Link to result range end node.
        /// </summary>
        /// <value>Link to result range end node.</value>
        [DataMember(Name="RangeEnd", EmitDefaultValue=false)]
        public AsposeWordsCloudDTODocumentPositionDto RangeEnd { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AsposeWordsCloudDTOSearchSearchResult {\n");
            sb.Append("  RangeStart: ").Append(RangeStart).Append("\n");
            sb.Append("  RangeEnd: ").Append(RangeEnd).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AsposeWordsCloudDTOSearchSearchResult);
        }

        /// <summary>
        /// Returns true if AsposeWordsCloudDTOSearchSearchResult instances are equal
        /// </summary>
        /// <param name="other">Instance of AsposeWordsCloudDTOSearchSearchResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AsposeWordsCloudDTOSearchSearchResult other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.RangeStart == other.RangeStart ||
                    this.RangeStart != null &&
                    this.RangeStart.Equals(other.RangeStart)
                ) && 
                (
                    this.RangeEnd == other.RangeEnd ||
                    this.RangeEnd != null &&
                    this.RangeEnd.Equals(other.RangeEnd)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.RangeStart != null)
                    hash = hash * 59 + this.RangeStart.GetHashCode();
                if (this.RangeEnd != null)
                    hash = hash * 59 + this.RangeEnd.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
