/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.com.aspose
{
    /// <summary>
    /// container class for xaml fixed save options
    /// </summary>
    [DataContract]
    public partial class AsposeWordsCloudDTOSavingXamlFixedSaveOptionsData :  IEquatable<AsposeWordsCloudDTOSavingXamlFixedSaveOptionsData>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AsposeWordsCloudDTOSavingXamlFixedSaveOptionsData" /> class.
        /// </summary>
        /// <param name="ResourcesFolder">Specifies the physical folder where resources (images and fonts) are saved when exporting a document to fixed page Xaml format.  Default is null..</param>
        /// <param name="ResourcesFolderAlias">Specifies the name of the folder used to construct image URIs written into an fixed page Xaml document.  Default is null..</param>
        public AsposeWordsCloudDTOSavingXamlFixedSaveOptionsData(string ResourcesFolder = default(string), string ResourcesFolderAlias = default(string))
        {
            this.ResourcesFolder = ResourcesFolder;
            this.ResourcesFolderAlias = ResourcesFolderAlias;
        }
        
        /// <summary>
        /// Specifies the physical folder where resources (images and fonts) are saved when exporting a document to fixed page Xaml format.  Default is null.
        /// </summary>
        /// <value>Specifies the physical folder where resources (images and fonts) are saved when exporting a document to fixed page Xaml format.  Default is null.</value>
        [DataMember(Name="ResourcesFolder", EmitDefaultValue=false)]
        public string ResourcesFolder { get; set; }

        /// <summary>
        /// Specifies the name of the folder used to construct image URIs written into an fixed page Xaml document.  Default is null.
        /// </summary>
        /// <value>Specifies the name of the folder used to construct image URIs written into an fixed page Xaml document.  Default is null.</value>
        [DataMember(Name="ResourcesFolderAlias", EmitDefaultValue=false)]
        public string ResourcesFolderAlias { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AsposeWordsCloudDTOSavingXamlFixedSaveOptionsData {\n");
            sb.Append("  ResourcesFolder: ").Append(ResourcesFolder).Append("\n");
            sb.Append("  ResourcesFolderAlias: ").Append(ResourcesFolderAlias).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AsposeWordsCloudDTOSavingXamlFixedSaveOptionsData);
        }

        /// <summary>
        /// Returns true if AsposeWordsCloudDTOSavingXamlFixedSaveOptionsData instances are equal
        /// </summary>
        /// <param name="other">Instance of AsposeWordsCloudDTOSavingXamlFixedSaveOptionsData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AsposeWordsCloudDTOSavingXamlFixedSaveOptionsData other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ResourcesFolder == other.ResourcesFolder ||
                    this.ResourcesFolder != null &&
                    this.ResourcesFolder.Equals(other.ResourcesFolder)
                ) && 
                (
                    this.ResourcesFolderAlias == other.ResourcesFolderAlias ||
                    this.ResourcesFolderAlias != null &&
                    this.ResourcesFolderAlias.Equals(other.ResourcesFolderAlias)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ResourcesFolder != null)
                    hash = hash * 59 + this.ResourcesFolder.GetHashCode();
                if (this.ResourcesFolderAlias != null)
                    hash = hash * 59 + this.ResourcesFolderAlias.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
