/* 
 * Aspose Words for Cloud Web API
 *
 * Version of Aspose.Words: 17.9.0.0 <br/>                                                      Version of Aspose.Words.Cloud: 17.8.0.0 <br/>                                                      Build number: 1
 *
 * OpenAPI spec version: v1.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.com.aspose
{
    /// <summary>
    /// This resonse should be returned by the service when handling:  GET http://api.aspose.com/v1.1/words/Test.doc/headersfooters/{0}
    /// </summary>
    [DataContract]
    public partial class AsposeWordsCloudDTODocumentElementsHeaderFootersHeaderFooterResponse :  IEquatable<AsposeWordsCloudDTODocumentElementsHeaderFootersHeaderFooterResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AsposeWordsCloudDTODocumentElementsHeaderFootersHeaderFooterResponse" /> class.
        /// </summary>
        /// <param name="HeaderFooter">HeaderFooter.</param>
        public AsposeWordsCloudDTODocumentElementsHeaderFootersHeaderFooterResponse(AsposeWordsCloudDTODocumentElementsHeaderFootersHeaderFooterDto HeaderFooter = default(AsposeWordsCloudDTODocumentElementsHeaderFootersHeaderFooterDto))
        {
            this.HeaderFooter = HeaderFooter;
        }
        
        /// <summary>
        /// HeaderFooter
        /// </summary>
        /// <value>HeaderFooter</value>
        [DataMember(Name="HeaderFooter", EmitDefaultValue=false)]
        public AsposeWordsCloudDTODocumentElementsHeaderFootersHeaderFooterDto HeaderFooter { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class AsposeWordsCloudDTODocumentElementsHeaderFootersHeaderFooterResponse {\n");
            sb.Append("  HeaderFooter: ").Append(HeaderFooter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as AsposeWordsCloudDTODocumentElementsHeaderFootersHeaderFooterResponse);
        }

        /// <summary>
        /// Returns true if AsposeWordsCloudDTODocumentElementsHeaderFootersHeaderFooterResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of AsposeWordsCloudDTODocumentElementsHeaderFootersHeaderFooterResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(AsposeWordsCloudDTODocumentElementsHeaderFootersHeaderFooterResponse other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.HeaderFooter == other.HeaderFooter ||
                    this.HeaderFooter != null &&
                    this.HeaderFooter.Equals(other.HeaderFooter)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.HeaderFooter != null)
                    hash = hash * 59 + this.HeaderFooter.GetHashCode();
                return hash;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
