#!/usr/bin/env python

class DocumentStatData(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'WordCount': 'int',
            'ParagraphCount': 'int',
            'PageCount': 'int',
            'PageStatData': 'list[PageStatData]'

        }

        self.attributeMap = {
            'WordCount': 'WordCount','ParagraphCount': 'ParagraphCount','PageCount': 'PageCount','PageStatData': 'PageStatData'}       

        self.WordCount = None # int
        self.ParagraphCount = None # int
        self.PageCount = None # int
        self.PageStatData = None # list[PageStatData]
        
