#!/usr/bin/env python

class DrawingObject(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'RenderLinks': 'list[Link]',
            'link': 'Link',
            'Width': 'float',
            'Height': 'float',
            'OleDataLink': 'Link',
            'ImageDataLink': 'Link'
            

        }

        self.attributeMap = {
            'RenderLinks': 'RenderLinks','link': 'link', 'Width': 'Width', 'Height': 'Height', 'OleDataLink': 'OleDataLink', 'ImageDataLink' : 'ImageDataLink'}       

        self.RenderLinks = None # list[Link]
        self.link = None # Link
        self.Width = None # float
        self.Height = None # float
        self.OleDataLink = None # Link
        self.ImageDataLink = None # Link        
        
