#!/usr/bin/env python

class SaveResult(object):
    """NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually."""


    def __init__(self):
        """
        Attributes:
          swaggerTypes (dict): The key is attribute name and the value is attribute type.
          attributeMap (dict): The key is attribute name and the value is json key in definition.
        """
        self.swaggerTypes = {
            'SourceDocument': 'Link',
            'DestDocument': 'Link',
            'AdditionalItems': 'list[Link]'

        }

        self.attributeMap = {
            'SourceDocument': 'SourceDocument','DestDocument': 'DestDocument','AdditionalItems': 'AdditionalItems'}       

        self.SourceDocument = None # Link
        self.DestDocument = None # Link
        self.AdditionalItems = None # list[Link]
        
